### ISSUE TITLE
ScrollView

### ISSUE THREAD

**Issue by tamil12440** [coinjar/react-native-wagmi-charts#84] opened 2022-03-10 10:46 UTC
How to add scroll in line and candle chart ?

**Comment by sqb47** [comment] 2024-04-15 14:09
looking for the same answer
i want to scroll horizontally

**Comment by honeybadger26** [comment] 2024-05-20 00:07
Duplicate of https://github.com/coinjar/react-native-wagmi-charts/issues/72

**Closed** 2024-05-20 00:07 UTC
