### ISSUE TITLE
How To Add Vertical Data and Horizontal Data on the Side and below Of The Chart.

### ISSUE THREAD

**Issue by mksmanish** [coinjar/react-native-wagmi-charts#131] opened 2023-04-21 04:05 UTC

**Comment by arancauchi** [comment] 2023-05-09 00:12
Hi @mksmanish i'm not really sure what you question means sorry. Do you mean x and y axis labels?

**Comment by dragonfi-kent** [comment] 2023-09-18 23:39
> Hi @mksmanish i'm not really sure what you question means sorry. Do you mean x and y axis labels?

Yes, X and Y labels. any way to achieve those?

**Comment by honeybadger26** [comment] 2024-04-25 23:51
Marking this as a duplicate of https://github.com/coinjar/react-native-wagmi-charts/issues/154

**Closed by honeybadger26** 2024-04-25 23:51 UTC
