### ISSUE TITLE
How To Add Vertical Data on The Side Of The Chart

### ISSUE THREAD

**Issue by mersimoski** [coinjar/react-native-wagmi-charts#118] opened 2023-01-23 20:03 UTC
Hi,

I love the charts and everything about them, but i was wondering if we can add vertical data on the side like the image below.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/62712311/214138349-ed864b0f-9b51-4d16-b9b6-727d5b0e547f.png">

**Comment by samartsevigor** [comment] 2023-05-24 10:25
No solution for this task?

**Comment by cihangir-mercan** [comment] 2024-03-23 11:33
hey any update?

**Comment by honeybadger26** [comment] 2024-04-25 23:52
Marking this as a duplicate of https://github.com/coinjar/react-native-wagmi-charts/issues/154

**Closed by honeybadger26** 2024-04-25 23:52 UTC
Labels: good first issue
