### ISSUE TITLE
How to put Xaxis and yaxis 

### ISSUE THREAD

**Issue by Gaurang-786** [coinjar/react-native-wagmi-charts#64] opened 2022-01-19 06:51 UTC

**Comment by yash-007** [comment] 2022-01-26 13:25
Hi, how do I zoomIn? I have a large list of data and it gets populated across the whole width, so I how to achieve scrollable/zoomin functionality?

**Comment by honeybadger26** [comment] 2024-04-25 23:55
Hey all, thanks for raising this. This issue is a duplicate of https://github.com/coinjar/react-native-wagmi-charts/issues/154 so please discuss more there.

Hi @theartificialguy. I left a comment [here](https://github.com/coinjar/react-native-wagmi-charts/issues/166#issuecomment-2068590237) explaining how you might acheive zoom in. Please discuss more about zoom in on that issue, thanks.

**Closed by honeybadger26** 2024-04-25 23:55 UTC
Labels: duplicate
